### ISSUE TITLE
Add "team" support

### ISSUE THREAD

**Issue by jcalcada** [martindstone/pagerduty-cli#1]
Hi Martin, was working with a customer yesterday and I pointed this to them. They who would like to use "users" with "teams" to be able to join those table. I imagine it's not trivial due to the different objects but it would be great to have it as other customers would also like to be able to have a user list with the teams they belong to.

**Comment by martindstone** [comment]
Hi Joe,

Team names can be shown by adding the -x option to the command. Is there additional team jnformation they would like to see?

**Comment by jcalcada** [comment]
Oh cool. Maybe that will work for Arlington.  

Thanks for the quick reply 

Joe Calcada.  416-605-7690.  
Sent via iPhone.

**Comment by martindstone** [comment]
You can now show any additional fields you like using JSONPath expressions as arguments to the `-k` flag, for example:

```
pd user:list -k 'teams[*].summary' -k 'teams[*].id'
```
