### ISSUE TITLE
Allow email based lookup [exact match]

### ISSUE THREAD

**Issue by akarande-sfdc** [martindstone/pagerduty-cli#10]
More of a feature request than an issue. Can email based lookup be added that matches the email exactly. Currently the command `pd user:list -e e.doe@mycompany.com -p` will match users that will have emails such as
`ellie.doe@mycompany.com, jose.doe@mycompany.com, jamie.doe@mycompany.com`. If an exact match option can be specified, then only the person with `e.doe@mycompany.com` will be picked.

Thanks!

**Comment by georgettica** [comment]
this matching also matches on username, so maybe the name is more unique?

**Comment by akarande-sfdc** [comment]
@georgettica you mean the first and last name? I think the names can have collisions. I think PagerDuty has a login email that is unique.

**Comment by martindstone** [comment]
@akarande-sfdc yeah, names don't have to be unique, but login email does. The default PD query parameter does substring match, but I could do some additional filtering when the results come back, how about I make the flag for exact match email be `-E`? Sounds ok?

**Comment by akarande-sfdc** [comment]
> @akarande-sfdc yeah, names don't have to be unique, but login email does. The default PD query parameter does substring match, but I could do some additional filtering when the results come back, how about I make the flag for exact match email be `-E`? Sounds ok?

That will be wonderful. All this while I was querying [Id and Email] and then filtering it based on the exact Id I wanted. But if you add the support with an extra parameter it will be very helpful. Thank you again for your work. This is very helpful.

**Comment by martindstone** [comment]
Hi @akarande-sfdc , I added `-E` to user:list, user:log and user:set in version 0.0.71, just published; I am going to close this issue but please reopen if it doesn't suit your needs... Thanks!

**Comment by akarande-sfdc** [comment]
@martindstone this is great. I just tested it out, works perfectly. Thank you so much for addressing this.
