### ISSUE TITLE
feat(merge) add merge incident functionality

### ISSUE THREAD

**Issue by georgettica** [martindstone/pagerduty-cli#11]
As seem here
https://github.com/openshift/ocm-container/blob/190235bfb9247bbbf137de2dc2e880d7633ff560/utils/bin/chgm#L120
The cli doesn't provide as of now the merge functionality

This feat is great in case incidents need to manually be merged for whatever reason

If this needs community PR, please note it and I will learn some JS and assemble a PR

**Comment by martindstone** [comment]
Hi @georgettica , thanks for reporting this. I agree that this would be a great addition to the CLI. I will get to work on it as soon as I have a chance.

Thanks!

**Comment by martindstone** [comment]
Hi @georgettica , I just published 0.0.72, which has `incident:merge` now... let me know if it's what you expected...

**Comment by georgettica** [comment]
this was tested and works as expected. removed manual rest command

**Comment by martindstone** [comment]
Thanks @georgettica ... I will close this now...
