### ISSUE TITLE
BLOCKED(filter): bump oclif/cli-ux once the related issue is fixed

### ISSUE THREAD

**Issue by georgettica** [martindstone/pagerduty-cli#15]
see https://github.com/oclif/cli-ux/issues/414

the issue I was facing was negating the search, as `!=` is not a valid operator in the `--filter` command

the solution would be noting these flags are derrived from there and waiting for the maintainer there to bump the docs to reflect how the filter query language can be used

**Comment by martindstone** [comment]
Looks like we did our best here but they are going a different direction… maybe there will be some improvements in @oclif/core or we could try to do some more sophisticated filtering on our own one day

**Comment by georgettica** [comment]
It's more of "I didn't do the doc change they wanted and lost interest"
It's a fairly easy fix and  just didn't invest enough time on it.

Maybe someone later will do that
