### ISSUE TITLE
Can we add pipe ability to rest:delete?

### ISSUE THREAD

**Issue by ajohnson-pdt** [martindstone/pagerduty-cli#16]
Not able to pass a piped list of services to rest:delete. This would be very helpful in cleaning up large swaths of unused services with similar names.

tried: `pd service:list --filter name={query string} -p | pd rest:delete -e /services -p`

**Comment by martindstone** [comment]
So the reason I have not done this (as well as the reason there are no other `*:delete` commands) is because I am terrified of the consequences of making a mistake. I am open to ideas here, but a `-p` flag to a delete command gives me some serious anxiety...

**Comment by ajohnson-pdt** [comment]
Possible to have a preview of the delete (or summary) and "ARE YOU ABSOLUTELY SURE?"

**Comment by martindstone** [comment]
Hmm... I could see doing that in a `service:delete` command... I am still a little scared to do it... maybe if you have to type something more than just `y`...

**Comment by ajohnson-pdt** [comment]
Full admission of wrongdoing, please provide your Venmo account for all liability damages. 😛

**Comment by martindstone** [comment]
Hey @ajohnson-pdt i put in a `user:delete` command... can you play around with it and let me know if that meets your needs? And if so, what other objects you would be interested in deleting like this?

**Comment by martindstone** [comment]
@ajohnson-pdt check out the new util:deleteresource command in 0.0.83 and let me know if that works for you?

**Comment by martindstone** [comment]
Closing this as I believe it’s resolved as noted above
