### ISSUE TITLE
Listing Services that have auto_pause_notifications_parameters enabled

### ISSUE THREAD

**Issue by BillSidney** [martindstone/pagerduty-cli#31]
Want to get a list of services that have  auto_pause_notifications_parameters enabled.
 
 Had expected `service:list` would do this.
 
 ```
   $ pd service:list -k=auto_pause_notifications_parameters.enabled   
```

**Comment by martindstone** [comment]
Hi, this will work in v0.1.5 now released as an RC, `pd update rc` to try it, `pd update stable` to switch back to 0.1.4... can you give it a try and let me know if it's resolved for you? Thanks

**Comment by BillSidney** [comment]
OUTSTANDING - That works Thank You!
