### ISSUE TITLE
Warning: pagerduty-cli update available from 0.1.5 to 0.1.6

### ISSUE THREAD

**Issue by akballow** [martindstone/pagerduty-cli#37]
when i do pd update i get 
pagerduty-cli: Updating CLI... already on version 0.1.5-d5a33df

**Comment by akballow** [comment]
Approaching 4 days an no comment???

**Comment by martindstone** [comment]
Sorry @akballow this is not my day job. I will be promoting 0.1.6 to stable soon, until then you can `pd update rc` to use 0.1.6 and avoid the warning. Let me know if that forks for you.

**Comment by martindstone** [comment]
0.1.6 is promoted to stable, you can `pd update stable` to go back to following stable releases. Please reopen if you have further issues.
