### ISSUE TITLE
install.sh syntax error

### ISSUE THREAD

**Issue by Matthew-Waterfield** [martindstone/pagerduty-cli#40]
The install script returns an error 

root: # sh -c "$(curl -sL https://raw.githubusercontent.com/martindstone/pagerduty-cli/master/install.sh)"
sh: line 6: [: missing `]'

Line
  if [ -e /usr/local/lib/pd -o -e /usr/local/bin/pd]; then
should be (space after pd before ]
  if [ -e /usr/local/lib/pd -o -e /usr/local/bin/pd ]; then

**Comment by martindstone** [comment]
Whoops! Will fix ASAP

**Comment by martindstone** [comment]
Ok @Matthew-Waterfield it’s fixed, sorry about that!

**Comment by 825i** [comment]
You can close this ticket now.
