### ISSUE TITLE
How to view timezones for schedules using cli?

### ISSUE THREAD

**Issue by 825i** [martindstone/pagerduty-cli#41]
Hi,

I am trying to view the timezones for all the schedules that we have via the CLI.

We have about 600+ schedules and have recently discovered some of our timezones are incorrectly set. This means people are missing duties and incidents.

I can't see a way to check this information with the CLI. It's basically not included at all from what I can see. For schedules there is quite a lot of information but TZ (Timezone) is not one of them. I'd obviously like to pull all TZ information and grep/awk through anything which is incorrectly set.

This information is available using the WebUI, see here:
![Screenshot 2022-11-08 at 13 36 32](https://user-images.githubusercontent.com/58630825/200554641-967b8d4d-9d09-42a0-827e-a6c41420ab85.png)

So technically it should be possible to get it via the CLI/api somehow.

P.S. I can see that when making a user via the CLI, it's possible to specify the TZ. Can we please have this for dumping schedule information too?

**Comment by 825i** [comment]
So far I can see this information if I do:

`pd schedule:show -i <schedule_id>`

![Screenshot 2022-11-08 at 13 43 25](https://user-images.githubusercontent.com/58630825/200555740-13a17995-9c18-43cd-a239-a74b00eff65d.png)

The problem with this, is that it only works for individual schedules. What if we have hundreds?

Secondly, it doesn't show me the exact UTC, like the above image in my first comment does. What if I am unsure what TZ "Warsaw" is specifically?

**Comment by 825i** [comment]
Alright, well I made myself a solution. It's not perfect and it doesn't make me feel clean, but it works!

`pd schedule:list -j | egrep '\"(name|time_zone)\b.*$$' | awk '/name/ {print $0} /time_zone/ {print $0 "\n"}'`

results:

```
pd schedule:list -j | egrep '\"(name|time_zone)\b.*$$' | awk '/name/ {print $0} /time_zone/ {print $0 "\n"}'
Getting schedules from PD 2/2 👍, 0/2 👎... done
    "name": "1st Line 7-17",
    "time_zone": "Europe/Helsinki",

    "name": "24-5",
    "time_zone": "Europe/Warsaw",

    "name": "Amazon Connect Test",
    "time_zone": "Europe/Warsaw",

    "name": "AWS Support",
    "time_zone": "Europe/Warsaw",

    "name": "Backup Squad",
    "time_zone": "Europe/Warsaw",
... etc
```

![gif](https://user-images.githubusercontent.com/58630825/200579674-8021f2bc-8aef-417d-abc0-53930c8372c8.gif)

Would still like to see this built into the CLI but I hope this helps someone with getting other information out of their **.json** results.

**Comment by martindstone** [comment]
Hi @825i sorry for the delay, you can add columns to the output for any field that appears in the JSON that comes from the fetch. To see time zone in the tabular output from schedule list, you can do `pd schedule list -k time_zone`

Hope this helps, can you let me know if that resolves the issue for you?

**Comment by martindstone** [comment]
Hi @825i I am going to close this issue since I think the above should resolve the issue for you... let me know if you have any trouble...

**Comment by 825i** [comment]
Hi mate, thanks for replying. Unfortunately in this case the columns are absolutely massive. As for a single schedule there may be over 100 users. So just one schedule displays 100 lines.

Would it be possible somehow to remove the other fields from the readout eg. Users, Escalation Policies etc. and just get:

* ID
* Name
* Time_zone

Here's an example of what I mean:

```
ID      Name                                    Users                      Escalation policies                              time_zone
 ─────── ─────────────────────────────────────── ────────────────────────── ──────────────────────────────────────────────── ───────────────
 P47R7L5 1st Line 7-17                           PagerDutyUser                                                               Europe/Helsinki
 P64JBZZ 24-5                                    PagerDutyUser                                                               Europe/Warsaw
                                                 non-sla-hours
 PDFD16Z Amazon Connect Test                     Grzegorz Prokopczyk                                                         Europe/Warsaw
 PT8KV6J AWS Support                             Karol Rogoziecki           Business Critical System Down                    Europe/Warsaw
                                                 Andrzej Skrzypczak         General Guidance
                                                 Sebastian Mocydlarz        Production System Down
                                                 PagerDutyUser              Production System Impaired
                                                 Jan Makowski               System Impaired
                                                 Jacek Jugowar
                                                 Adam Skurtys
                                                 Paweł Dzwonkowski
                                                 Maciej Wilczyński
                                                 Jędrzej Piszcz
                                                 Jakub Godlewski
```

**Comment by 825i** [comment]
Nvm I actually put my brain into gear and I see there is a way to filter columns, so:

```
➜  ~ pd schedule list -k time_zone --columns=id,name,time_zone
Getting schedules from PD 3/3 👍, 0/3 👎... done
 ID      Name                                    time_zone
 ─────── ─────────────────────────────────────── ───────────────
 P47R7L5 1st Line 7-17                           Europe/Helsinki
 P64JBZZ 24-5                                    Europe/Warsaw
 PDFD16Z Amazon Connect Test                     Europe/Warsaw
 PT8KV6J AWS Support                             Europe/Warsaw
 PEQ5E4Z Backup Squad                            Europe/Warsaw
```

I love you. This is absolutely amazing. No more piping everything through egrep and awk. Oh my g*d 👯

**Comment by martindstone** [comment]
Great work, and thank you!
