### ISSUE TITLE
Warning: pagerduty-cli update available from 0.1.6 to 0.1.13.

### ISSUE THREAD

**Issue by mwarkentin** [martindstone/pagerduty-cli#49]
Great looking tool, thanks!

I'm getting this warning whenever I run a `pd` command:

```
Warning: pagerduty-cli update available from 0.1.6 to 0.1.13.
```

I just installed via the recommended method, and I've tried running `pd update` but am still getting this:

```
❯ pd update
pagerduty-cli: Updating CLI from 0.1.6 to 0.1.6-996afd9... done
```

Any suggestions?

**Comment by mwarkentin** [comment]
Cool, I'll wait for the official release.

**Comment by martindstone** [comment]
Hi @mwarkentin, I just promoted 0.1.15 to stable, and it should prompt you to update and then actually update... can you check it out and let me know? Thanks...

**Comment by mwarkentin** [comment]
Not sure if it would've prompted me but the update worked well:

```
❯ pd update
pagerduty-cli: Updating CLI from 0.1.6-996afd9 to 0.1.15-5b588fc... done
```
