### ISSUE TITLE
when installing the latest version (0.0.70) the installation complains on `deprecated axios@0.20.0`

### ISSUE THREAD

**Issue by georgettica** [martindstone/pagerduty-cli#9]
migration to the new version will assist in making this repo less scary to install

``` 
npm install -g pagerduty-cli@0.0.70
 ---> Running in dd37eceed07c
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
```

**Comment by martindstone** [comment]
Hi @georgettica , I updated axios to v0.21 in version v0.0.71, just published... I am going to close this issue but please reopen if you see any problems... Thanks!
